### ISSUE TITLE
有关于WIndows下使用问题

### ISSUE THREAD

**Issue by gameover453** [LubyRuffy/wyquery#1]
HI  作者你好
感谢提供非常方便wyquery

我在Windows下使用发生了一些问题，在这里记录下来希望能为您下一版本或者其他人提供帮助
我的系统是Win10 X64

TZInfo::DataSourceNotFound 错误：
修改根目录下Gemfile
追加一行:
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
若为32位系统则追加：
gem 'tzinfo-data', platforms: [:mingw, :mswin]

Rails-4, ExecJS::ProgramError 错误（这个错误应该仅限WIn下了）:
coffee-script 1.9.X在win下表现不佳 替换掉
在Gemfile文件下追加一行:
gem 'coffee-script-source', '1.8.0'
执行
bundle update coffee-script-source

Thanks  LubyRuffy : ）

**Comment by LubyRuffy** [comment]
@gameover453 thanks，有没有通用的方法保持Gemfile跨平台支持？我尝试加过，好像不能很好的解决平台定义冲突问题，所以windows的我都没有提交（我也在windows下调试，不过代码分开管理）。

**Comment by LubyRuffy** [comment]
更新了，支持64位系统
